apiVersion: apps.example.com/v1
kind: ConfigMapSync
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator-example
    app.kubernetes.io/managed-by: kustomize
  name: configmapsync-sample
spec:
  # TODO(user): Add fields here
